receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  logging:

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  file:
    path: /etc/output/logs.json
    
  #otlp/elastic:
  #  endpoint: "http://elasticsearch:9300"
  #  tls:
  #    insecure: true
  #elasticsearch:
  #  endpoints: [elasticsearch:9200]
  #  insecure: true
  #elastic:
  #  apm_server_url: "elasticsearch:9200"
  #  tls:
  #    insecure: true
    
  otlp/honeycomb:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "16962c107a9756ea77c5d7a0766a3a1f"
      "x-honeycomb-dataset": "Svejik"
   
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
      
processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, otlp/honeycomb, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging, file]